### ISSUE TITLE
Provide practical measures of performance for classification datasets

### ISSUE THREAD

**Issue by maitra** [DormanLab/kmodes#1]
The current code provides the maximum AR (or other measures) from n initializations, and also an average AR. From a practical perspective, it would make sense to have the AR corresponding to the lowest objective function, in order to assess performance because in a real-life dataset, we would not know the actual classification, and so the AR corresponding to the best objective function is a more practical assessor. Can this please be included?

**Comment by kdorman** [comment]
Please see Best AR, Best MI, and Best VI for the Adjusted RAND Index, Normalized Mutual Information, and Normalized Variation of Information at the best achieved objective function now output to screen or file. In the case that the best objective is reached multiple times with different solutions, we report the worst of the computed ARI, NMI, and NVI.
